name: "Flutter CI"
on:
    push:
        paths:
            - 'currency_converter/**'

jobs:
    check-format:
        runs-on: ubuntu-latest
        steps:
            - name: "Get Code"
              uses: actions/checkout@v2
            - name: "Install Flutter"
              uses: subosito/flutter-action@v1
              with:
                  channel: stable
            - name: "Change Directory"
              run: cd currency_converter/
            - name: "Setup Project"
              run: flutter pub get
            - name: "Check Format"
              run: flutter format -l 120 --set-exit-if-changed .
    analyze-code:
        runs-on: ubuntu-latest
        steps:
            - name: "Get Code"
              uses: actions/checkout@v2
            - name: "Install Flutter"
              uses: subosito/flutter-action@v1
              with:
                  channel: stable
            - name: "Change Directory"
              run: cd currency_converter/
            - name: "Setup Project"
              run: flutter pub get
            - name: "Analyze code"
              run: flutter analyze

