name: "Flutter CI"
on:
    push:
        paths:
            - 'photo_finder/**'

jobs:
    check-format:
        runs-on: ubuntu-latest
        steps:
            - name: "Get Code"
              uses: actions/checkout@v2
            - name: "Install Flutter"
              uses: subosito/flutter-action@v1
              with:
                  channel: stable
            - name: "Setup Project"
              working-directory: ./photo_finder
              run: flutter pub get
            - name: "Check Format"
              working-directory: ./photo_finder
              run: flutter format -l 120 --set-exit-if-changed .
    analyze-code:
        runs-on: ubuntu-latest
        steps:
            - name: "Get Code"
              uses: actions/checkout@v2
            - name: "Install Flutter"
              uses: subosito/flutter-action@v1
              with:
                  channel: stable
            - name: "Setup Project"
              working-directory: ./photo_finder
              run: flutter pub get
            - name: "Analyze code"
              working-directory: ./photo_finder
              run: flutter analyze

